# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoomApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoomApp

  target 'LoomAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoomAppUITests' do
    # Pods for testing
  end

pod "MBCircularProgressBar"
pod 'SOTabBar'
pod 'SideMenu'
pod 'IQKeyboardManagerSwift'
pod 'Alamofire'
pod 'Toast-Swift', '~> 5.0.1'
pod 'SwiftLoader', '1.0.0'
pod 'iOSDropDown'
pod 'FlagPhoneNumber'
pod 'SwiftPopMenu'
pod 'SDWebImage', '~> 5.0'
pod 'SVGKit'
pod 'LiteStarView', '~> 1.0'
pod 'Cosmos'
pod 'razorpay-pod'
pod 'Socket.IO-Client-Swift'
pod 'Firebase'
pod 'Firebase/Messaging'
end
